openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: This is a swagger ui for out trennkodus API
paths:
    /exercises:
        post:
            requestBody:
                description: A new exercise to be created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/error'
                        examples:
                            error:
                                value:
                                    error: One or all params are missing
                required: true
            tags:
                - new-exercise
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/new-exercise'
                    description: created a exercise
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/new-exercise'
                            examples:
                                error:
                                    value:
                                        name: some text
                                        set: 29.13
                                        repesition: 72.96
                    description: One or all params are missing
            summary: Creates a exercise
            description: Creates a new exercise
    '/exercises/:id':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of a given exercise:
                                    value: '{id: 1, name: "push-up", repetition: 10, set: 3}'
                    description: Returns full details of a given id exercise
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Exercise /w+ was not found:
                                    value:
                                        error: Exercise \w+ was not found in exercise array.
                    description: Exercise was not found in exercises array
            operationId: id
            summary: Get full details of a exercise
            description: Returns full details of a given id exercise
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        new-exercise:
            title: Root Type for new-exercise
            description: Creates a new exercise
            required:
                - name
                - repesition
                - set
            type: object
            properties:
                name:
                    type: string
                set:
                    format: float
                    type: number
                repesition:
                    format: float
                    type: number
            example:
                name: push-up
                set: 3
                repesition: 10
